export const USER_REPOSITORY_PROVIDER = 'USER_REPOSITORY_PROVIDER';
export const ROLE_REPOSITORY_PROVIDER = 'ROLE_REPOSITORY_PROVIDER';
export const ENDPOINT_REPOSITORY_PROVIDER = 'ENDPOINT_REPOSITORY_PROVIDER';
export const ACTION_REPOSITORY_PROVIDER = 'ACTION_REPOSITORY_PROVIDER';
