name: Build and Publish Package

on:
  push:
    branches:
      - pack-cqrs-authentication-rbac

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: NPM_PACK

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true  # Ensure authentication

      - name: Authenticate with npm
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: |
          cd packages/authentication
          npm install

      - name: Build package
        run: |
          cd packages/authentication
          npm run build

      # Publish the package to npm
      - name: Publish to npm
        run: |
          cd packages/authentication
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  notify-on-failure:
    environment: NPM_PACK
    needs: build-and-publish
    if: failure() 
    runs-on: ubuntu-latest

    steps:
      - name: Send failure notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "🚨 GitHub Actions Workflow Failed!"
          body: "The workflow for `pack-cqrs-authentication-rbac` branch has failed. Check the logs for more details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          to: "phanhoangkha02@gmail.com"
          from: "GitHub Actions"