name: Build and Publish Package

on:
  push:
    branches:
      - pack-cqrs-authentication-rbac

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: NPM_PACK

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org/'
          always-auth: true  # Ensure authentication

      - name: Authenticate with npm
        run: npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: |
          cd packages/authentication
          npm install

      - name: Unit test
        run: |
          cd packages/authentication
          npm run test

      - name: Wait for PostgreSQL to be ready
        run: |
          until pg_isready -h localhost -p 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done

      - name: E2e test
        run: |
          cd packages/authentication
          npm run test:e2e
        env:
          PG_MAIN_DB_CONNECTION_STRING: postgres://postgres:postgres@localhost:5432/testdb

      - name: Build package
        run: |
          cd packages/authentication
          npm run build

      # Publish the package to npm
      - name: Publish to npm
        run: |
          cd packages/authentication
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}